<?php 
include('includes/dbsmain.inc.php');
include('site-main-query.php');
$site_url=$compDATA['admin_website_url'];
$total_marketplace = db_scalar("select COUNT(category_id) from tbl_marketplace");
header("Content-Type: application/xml; charset=utf-8");

echo '<?xml version="1.0" encoding="UTF-8"?>'.PHP_EOL; 

echo '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd">'.PHP_EOL;

echo "<!-- Sitemap Generated by Vyaparbharat -->";

for($i=1;$i<=$total_marketplace;$i++){
echo '<sitemap>'. PHP_EOL;
 echo '<loc>'.$site_url.'/sitemap'. $i .'.xml</loc>'. PHP_EOL;
echo '</sitemap>'. PHP_EOL;
}
echo '</sitemapindex>'. PHP_EOL;
?>